name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/checkout@v2.3.2

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        group: Tests on Node v${{ matrix.node }}
        cache-key: node-v${{ matrix.node }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
        start: yarn start
        wait-on: 'http://localhost:3000'
        browser: chrome

    - name: Export screenshots (on failure only)
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: tests/cypress/screenshots

    - name: Export screen recordings (on failure only)
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-videos
        path: tests/cypress/videos

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/checkout@v2.3.2

    - name: Install dependencies
      run: yarn install

    - name: Build packages dependencies
      run: yarn build:packages
