name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - uses: actions/checkout@v2.3.2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        command: yarn run startandtest

    - name: Export screenshots of failed tests
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: tests/cypress/screenshots

    - name: Export screen recording of executed tests
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: cypress-videos
        path: tests/cypress/videos
